# saleRecordDB
saleRecordConnDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_nhub?charset=utf8
# cslDB
cslConnDatabase:
  driver: mssql
  connection: server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300
# clearanceForSaleRecordDB
cfsrConnDatabase:
  driver: mysql
  connection: mslv2_app:Eland^123@tcp(106.14.242.171:3306)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC
# placeManagementDB
pmConnDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_place_management?charset=utf8
productDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_product?charset=utf8&parseTime=True&loc=UTC
colleagueAuthDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_common_colleague_auth?charset=utf8&parseTime=True&loc=UTC
services:
  placeManagementApi:  http://place-management-api.pangpang-brand-qa:8080
  getTokenApi: https://qa.p2shop.com.cn/pangpang-common/portal-api/login?tenantCode=pangpang
getTokenUser:
  userName: qa.pangpang
  password: 1111
appenv: mslv2-qa
serviceName: clearance-adapter-for-sale-record