# saleRecordDB
saleRecordConnDatabase:
  driver: mysql
  connection: root:root@tcp(localhost:3307)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC
# cslDB
cslConnDatabase:
  driver: mssql
  connection: server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300
# clearanceForSaleRecordDB
cfsrConnDatabase:
  driver: mysql
  connection: mslv2_app:Eland^123@tcp(10.173.208.142:3307)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC
appenv: mslv2-staging
serviceName: clearance-adapter-for-sale-record