# saleRecordDB
saleRecordConnDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_brand_nhub?charset=utf8
# cslDB
cslConnDatabase:
  driver: mssql
  # connection: server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300
  connection: server=10.201.10.120;user id=CSL_APP;password=Wldkdydn09#;database=CSL;connection timeout=10
# clearanceForSaleRecordDB
cfsrConnDatabase:
  driver: mysql
  connection: mslv2_app:0pL6LA#7@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC
# placeManagementDB
pmConnDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_brand_place_management?charset=utf8
productDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_brand_product?charset=utf8&parseTime=True&loc=UTC
colleagueAuthDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_common_colleague_auth?charset=utf8&parseTime=True&loc=UTC
shopEmployeeDatabase:
  driver: mysql
  connection: mslv2_app:0pL6LA#7@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/mslv2_shop_employee?charset=utf8&parseTime=True&loc=UTC
mslv2ReadonlyDatabase:
  driver: mysql
  connection: mslv2_readonly:o0V^c3gB@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com:3306)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=Local
behaviorLog:
  kafka:
    brokers:
      - ikafka01o.p2shop.com.cn:9094
      - ikafka02o.p2shop.com.cn:9094
      - ikafka03o.p2shop.com.cn:9094
    topic: behaviorlog
    ssl:
      enable: true
      clientCertFile: ./certfile/client.cer.pem
      clientKeyFile: ./certfile/client.key.pem
      caCertFile: ./certfile/server.cer.pem
services:
  placeManagementApi: https://p2shop.com.cn/pangpang-brand/place-management-api
  # getTokenApi: https://qa.p2shop.com.cn/pangpang-common/portal-api/login?tenantCode=pangpang
  getTokenApi: http://colleague-login-api.pangpang-common:8082/api
  membership: https://p2shop.com.cn/pangpang-brand/benefit-api
  exchangeApi: https://gateway.p2shop.com.cn/mslv2/exchange-api
getTokenUser:
  appId: d11cbd31d042462e893d627dfcea0c4e
  appSecretKey: 4c4458869c344f3faa6dd8485dab9665
appenv: mslv2-production
serviceName: clearance-adapter-for-sale-record