# saleRecordDB
saleRecordConnDatabase:
  driver: mysql
  connection: root:root@tcp(localhost:3307)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC
# cslDB
cslConnDatabase:
  driver: mssql
  connection: server=localhost;user id=sa;password=passwordroot;database=CSL;connection timeout=30
# clearanceForSaleRecordDB
cfsrConnDatabase:
  driver: mysql
  connection: mslv2_app:Eland^123@tcp(10.30.8.55:3306)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC
appenv: mslv2-qa
serviceName: clearance-adapter-for-sale-record