# saleRecordDB
saleRecordConnDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_nhub?charset=utf8
# cslDB
cslConnDatabase:
  driver: mssql
  connection: server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300
# clearanceForSaleRecordDB
cfsrConnDatabase:
  driver: mysql
  connection: mslv2_app:Eland^123@tcp(106.14.242.171:3306)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC
# placeManagementDB
pmConnDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_place_management?charset=utf8
productDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_product?charset=utf8&parseTime=True&loc=UTC
colleagueAuthDatabase:
  driver: mysql
  connection: pangpang_app:Eland^123@tcp(106.14.242.171:3306)/pangpang_common_colleague_auth?charset=utf8&parseTime=True&loc=UTC
shopEmployeeDatabase:
  driver: mysql
  connection: mslv2_app:Eland^123@tcp(106.14.242.171:3306)/mslv2_shop_employee?charset=utf8&parseTime=True&loc=UTC
mslv2ReadonlyDatabase:
  driver: mysql
  connection: qa_readonly:Eland^123@tcp(106.14.242.171:3306)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=Local
services:
  placeManagementApi: https://qa.p2shop.com.cn/pangpang-brand/place-management-api
  # getTokenApi: https://qa.p2shop.com.cn/pangpang-common/portal-api/login?tenantCode=pangpang
  getTokenApi: https://qa.p2shop.com.cn/pangpang-common/colleague-login-api/api
  membership: https://qa.p2shop.com.cn/pangpang-brand/benefit-api
  exchangeApi: https://qa.p2shop.com.cn/mslv2/exchange-api
  saleRecordPostProcessApi: https://qa.p2shop.com.cn/pangpang-brand/sale-record-postprocess-api
getTokenUser:
  appId: d11cbd31d042462e893d627dfcea0c4e
  appSecretKey: 4c4458869c344f3faa6dd8485dab9665
appenv: mslv2-qa
serviceName: clearance-adapter-for-sale-record