
cslConnString: "server=localhost;user id=sa;password=passwordroot;database=CSL;connection timeout=30"

saleRecordConnString: "root:root@tcp(localhost:3307)/pangpang_brand_nhub?charset=utf8&parseTime=True&loc=UTC"
