# saleRecordDB
saleRecordConnDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_brand_nhub?charset=utf8
# cslDB
cslConnDatabase:
  driver: mssql
  # connection: server=10.201.10.167;user id=CSL_DEV;password=8zMb4ZP1;database=CSL;connection timeout=300
  connection: server=10.201.10.120;user id=CSL_DEV;password=#fldzm49.7;database=CSL;connection timeout=300
# clearanceForSaleRecordDB
cfsrConnDatabase:
  driver: mysql
  connection: mslv2_app:0pL6LA#7@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/mslv2_clearance?charset=utf8&parseTime=True&loc=UTC
# placeManagementDB
pmConnDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_brand_place_management?charset=utf8
productDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_brand_product?charset=utf8&parseTime=True&loc=UTC
colleagueAuthDatabase:
  driver: mysql
  connection: pangpang_app:7#dIQ2qY@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/pangpang_common_colleague_auth?charset=utf8&parseTime=True&loc=UTC
shopEmployeeDatabase:
  driver: mysql
  connection: mslv2_app:0pL6LA#7@tcp(rm-uf65796v5j1t257t19o.mysql.rds.aliyuncs.com)/mslv2_shop_employee?charset=utf8&parseTime=True&loc=UTC
services:
  placeManagementApi: https://p2shop.com.cn/pangpang-brand/place-management-api
  # getTokenApi: https://qa.p2shop.com.cn/pangpang-common/portal-api/login?tenantCode=pangpang
  getTokenApi: http://colleague-login-api.pangpang-common:8082/api
  membership: https://p2shop.com.cn/pangpang-brand/benefit-api
getTokenUser:
  appId: d11cbd31d042462e893d627dfcea0c4e
  appSecretKey: 4c4458869c344f3faa6dd8485dab9665
appenv: mslv2-production
serviceName: clearance-adapter-for-sale-record