FROM pangpanglabs/golang:builder-beta AS builder

WORKDIR /go/src/clearance/clearance-adapter-for-sale-record

COPY . .
# create kafka certfile dir
RUN mkdir -p certfile

RUN go get github.com/pangpanglabs/goetl
# disable cgo
ENV CGO_ENABLED=0
# build steps
RUN cd ./cmd/api-app && echo ">>> 1: go version" && go version \
    && echo ">>> 2: go get" && go get -v -d \
    && echo ">>> 3: go build" && go build -o clearance-adapter-for-sale-record-api

# make application docker image use alpine
FROM pangpanglabs/alpine-ssl
WORKDIR /go/bin
# copy config files to image
COPY --from=builder /go/src/clearance/clearance-adapter-for-sale-record/*.yml ./
# copy kafka cert files to image
COPY --from=builder /go/src/clearance/clearance-adapter-for-sale-record/certfile ./certfile
# copy execute file to image
COPY --from=builder /go/src/clearance/clearance-adapter-for-sale-record/cmd/api-app/clearance-adapter-for-sale-record-api ./
EXPOSE 8000
CMD ["./clearance-adapter-for-sale-record-api","api"]